### ISSUE TITLE
Transparency doesn't work

### ISSUE THREAD

**Issue by tunix** [tunix/alacritty-snap#2]
After upgrading from Ubuntu 20.04 LTS to 20.10, I couldn't have transparency working with this snap. Up until that, I wasn't including GL libraries into snap and wasn't configuring properly so I added them. But it still doesn't work. I've read through almost all tickets in Alacritty's github issues page but couldn't find a proper solution. (they've mentioned the lack of a compositor but I'm not sure that's really related to this case)

Any help would be appreciated!

**Comment by jameschensmith** [comment]
From Alacritty output, I'm noticing the error below:

```
libGL error: MESA-LOADER: failed to open nouveau (search paths /snap/alacritty/x3/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: nouveau
libGL error: MESA-LOADER: failed to open nouveau (search paths /snap/alacritty/x3/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: nouveau
libGL error: MESA-LOADER: failed to open swrast (search paths /snap/alacritty/x3/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: swrast
```

I didn't check this when I was on Ubuntu 20.04, but this could be applicable. Going to dig a bit deeper into this error.

**Comment by jameschensmith** [comment]
Found a thread you posted in Snapcraft ([view here](https://forum.snapcraft.io/t/issue-with-gl-after-upgrading-to-20-10/22272)), which provides some good context of what you've tried so far :slightly_smiling_face:

**Comment by jameschensmith** [comment]
From [this mesa issue note](https://gitlab.freedesktop.org/mesa/mesa/-/issues/3477#note_614647), I ran Alacritty again with `LIBGL_DEBUG=verbose`. Now, there's a clearer issue seen:

<details>
<summary>CLI output</summary>

```
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/<USER>/.drirc: No such file or directory.
libGL: using driver nouveau for 8
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/<USER>/.drirc: No such file or directory.
libGL: pci id for fd 8: 10de:2187, driver nouveau
libGL: MESA-LOADER: failed to open /snap/alacritty/x2/usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so: libffi.so.7: cannot open shared object file: No such file or directory
libGL error: MESA-LOADER: failed to open nouveau (search paths /snap/alacritty/x2/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: nouveau
libGL: using driver nouveau for 8
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/<USER>/.drirc: No such file or directory.
libGL: pci id for fd 8: 10de:2187, driver nouveau
libGL: MESA-LOADER: failed to open /snap/alacritty/x2/usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so: libffi.so.7: cannot open shared object file: No such file or directory
libGL error: MESA-LOADER: failed to open nouveau (search paths /snap/alacritty/x2/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: nouveau
libGL: MESA-LOADER: failed to open /snap/alacritty/x2/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so: libffi.so.7: cannot open shared object file: No such file or directory
libGL error: MESA-LOADER: failed to open swrast (search paths /snap/alacritty/x2/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: swrast
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/<USER>/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/<USER>/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/<USER>/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/<USER>/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/<USER>/.drirc: No such file or directory.
```
</details>

The message to pay attention to is `libffi.so.7: cannot open shared object file: No such file or directory`. From [this Ask Ubuntu response](https://askubuntu.com/a/1300763), we can see that from 20.04 to 20.10, `libffi` was updated from 7 to 8.

So, I think this could be the issue. I've tried to add `libffi7` as a staging package so that it can find the shared object file, but was unsuccessful. I'm still quite new to snaps, so maybe you have better knowledge on how to address this? :slightly_smiling_face:

**Comment by tunix** [comment]
Awesome! 🚀  Btw thank you for sharing the forum threads I've created as I've forgotten about them. 😆  Clearly, I thought that taking screenshots in fullscreen was working but it doesn't. I'll check if the library fixes that as well.

This is a good direction for me! I'll see what I can do and will let you know. Thanks @jameschensmith !

**Comment by tunix** [comment]
OK. So far, all my attempts have failed. Currently we're using `core20` as base image which means 20.04 LTS so we actually have access to `libffi7` package. I placed it within staged-packages (so I included it into the snap -- which means we don't have to depend on host system the snap is installed on) but alacritty still cannot find it. I've tried placing it within mesa block but that also didn't work. I remember that LIBGL paths are defined by `snapcraft-desktop-helpers` part. I'm probably missing something. Will try tomorrow.

**Comment by jameschensmith** [comment]
@tunix, it worked for me when I did the manual download from [this Ask Ubuntu response](https://askubuntu.com/questions/1286772/libffi-so-7-cannot-open-shared-object-file-no-such-file-or-directory/1300763#1300763) (granted, this won't be the end-all solution, but it will work if you just want to validate on your end that transparency is working).

One way we can see if `libffi` is included in the shared object libraries is to run `ldconfig -p |  grep ffi`.

**Comment by tunix** [comment]
I believe it worked for you because you installed that library on your host, am I correct? However for snaps, it's different. If the snap doesn't include (and configured) the library properly then it looks on the host. I seem to have libffi6 & libffi8 on my host (despite I'm on 20.10) but not libffi7. (🤔) And since the snap can't find it (despite it's available in snap) transparency still doesn't work for me. So I need to figure out why the snap can't find it.

**Comment by jameschensmith** [comment]
> I believe it worked for you because you installed that library on your host, am I correct?

Correct, I installed it on my host for validation purposes. This for sure isn't the desired solution. I appear to only have `libffi8` on my host after upgrading to 20.10. It seems the snap is looking at host libraries. Maybe because it's a classic snap? :thinking:

**Comment by jameschensmith** [comment]
The diff below works :blush: Let me know your thoughts.

<details>
<summary>Git diff</summary>

```diff
diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
index 911a575..21b0b57 100644
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -15,6 +15,7 @@ apps:
         desktop: usr/share/applications/Alacritty.desktop
         environment:
             LC_ALL: C.UTF-8
+            LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"
 
 parts:
     desktop-glib-only:
@@ -66,6 +67,7 @@ parts:
             - libxcb1-dev
             - libgl1-mesa-dev
         stage-packages:
+            - libffi7
             - libfontconfig1
             - libfreetype6
             - libpng16-16
```
</details>

**Comment by tunix** [comment]
Yes it does! 🎉  Thank you @jameschensmith ! Would you also consider being a collaborator?

**Comment by jameschensmith** [comment]
Awesome, my pleasure! :grin: I'd love to be a collaborator :blush: :+1:
