### ISSUE TITLE
Cursor theme is not properly configured

### ISSUE THREAD

**Issue by tunix** [tunix/alacritty-snap#4]
We need to work on the cursor theme. I'm not really aware if there is another issue about theming. I think snapcraft-desktop-helpers may fix this issue but I'm not sure how. Couldn't find any relevant info on the forums as well. I'll create a new forum thread and update here.

**Comment by tunix** [comment]
[Looks like](https://forum.snapcraft.io/t/custom-snap-shows-default-x11-cursor/23958/2) we'll need to change some env vars that are defined by snapcraft-desktop-helpers. Probably where most major distros install their cursor themes into.

**Comment by jameschensmith** [comment]
This is an interesting one :thinking: It doesn't seem like the VS Code supports this (I could be wrong on this, as I only tested with cursor size so far). Also, trying to add `XCURSOR_PATH` as an environment variable won't work out, as the helper scripts re-export `XCURSOR_PATH`, which overwrites anything we put in `snapcraft.yaml`. I'll see if I can dig a bit deeper.

**Comment by jameschensmith** [comment]
Okay, this is for my desktop specifically, but this may help steer us in the right direction. I'm on Ubuntu 20.10 (Gnome DE), and when I update my cursor size, it updates my gsettings.

Output on Gnome Terminal:
```
$ gsettings get org.gnome.desktop.interface cursor-size
64
```

Output on Alacrity Snap:
```
$ gsettings get org.gnome.desktop.interface cursor-size
24
```

So, at least for Gnome, the Snap would need to be able to read the user's gsettings. Based on the documentation [here](https://wiki.archlinux.org/index.php/Cursor_themes#GNOME), if we had the ability to append paths to `XCURSOR_PATH`, we could possibly address this. This is just initial observation, though :blush: Let me know what you think!

**Comment by tunix** [comment]
I'm not sure whether gsettings are relevant in this context. (Alacritty probably doesn't know anything about it and I think we're in a non-gnome/gtk related environment within the snap)

I recently added `snap/local/xdg-wrapper` script which actually reverts the affects of snapcraft-desktop-helpers and overwrites some env vars. I think a similar approach is needed for env vars like XCURSOR_PATH etc.

**Comment by tunix** [comment]
@jameschensmith - can you please test the PR I've just created? thanks!

**Comment by jameschensmith** [comment]
> I'm not sure whether gsettings are relevant in this context. (Alacritty probably doesn't know anything about it and I think we're in a non-gnome/gtk related environment within the snap)

Hmm, okay. That makes sense. The only thing is that even with the fix you did, it only solves cursor theme and not size. I would love to see this addressed in the future, but since this issue's topic is on the theme, let's resolve that first and foremost :slightly_smiling_face: :+1: 

> I recently added `snap/local/xdg-wrapper` script which actually reverts the affects of snapcraft-desktop-helpers and overwrites some env vars. I think a similar approach is needed for env vars like XCURSOR_PATH etc.

Ah! So this is an override script. Nice! That helps :sweat_smile:
